**Categorical Data Practices**

| دستور                    | کاربرد                        |
| ------------------------ | ----------------------------- |
| `set_index()`            | تبدیل ستون به Index           |
| `reset_index()`          | برگرداندن Index به ستون       |
| `reset_index(drop=True)` | حذف Index قبلی                |
| `sort_index()`           | مرتب‌سازی بر اساس Index       |
| `reindex()`              | تنظیم مجدد ترتیب/مجموعه Index |
| MultiIndex               | Index چندسطحی                 |


---

In [4]:
import pandas as pd

#####Exercise — AI Experiment Index Management
```text
experiments = pd.DataFrame({
    "experiment_id": [
        "exp_003",
        "exp_001",
        "exp_002",
        "exp_004"
    ],
    "model": [
        "ResNet",
        "CNN",
        "ViT",
        "CNN"
    ],
    "dataset": [
        "CIFAR10",
        "MNIST",
        "CIFAR10",
        "MNIST"
    ],
    "accuracy": [
        0.94,
        0.91,
        0.96,
        0.93
    ]
})
Tasks
Set experiment_id as the DataFrame index.
Display the current index.
Check whether the index is unique.
Sort the DataFrame by its index.

Reindex the DataFrame in this order:

exp_004
exp_002
exp_001
exp_003
Reset the index and keep experiment_id as a normal column.
Create a MultiIndex using model and dataset.
Sort the MultiIndex.
Reset the MultiIndex back to normal columns.
In a comment, explain the difference between set_index() and reindex().

In [5]:
experiments = pd.DataFrame({
    "experiment_id": [
        "exp_003",
        "exp_001",
        "exp_002",
        "exp_004"
    ],
    "model": [
        "ResNet",
        "CNN",
        "ViT",
        "CNN"
    ],
    "dataset": [
        "CIFAR10",
        "MNIST",
        "CIFAR10",
        "MNIST"
    ],
    "accuracy": [
        0.94,
        0.91,
        0.96,
        0.93
    ]
})

experiments = experiments.set_index("experiment_id")

experiments

                model  dataset  accuracy
experiment_id
exp_003        ResNet  CIFAR10      0.94
exp_001           CNN    MNIST      0.91
exp_002           ViT  CIFAR10      0.96
exp_004           CNN    MNIST      0.93

In [6]:
experiments.index

Index(['exp_003', 'exp_001', 'exp_002', 'exp_004'], dtype='str', name='experiment_id')

In [7]:
experiments.index.is_unique

True

In [8]:
experiments = experiments.sort_index()

experiments

                model  dataset  accuracy
experiment_id
exp_001           CNN    MNIST      0.91
exp_002           ViT  CIFAR10      0.96
exp_003        ResNet  CIFAR10      0.94
exp_004           CNN    MNIST      0.93

In [9]:
new_order = [
    "exp_004",
    "exp_002",
    "exp_001",
    "exp_003"
]

experiments = experiments.reindex(new_order)

experiments

                model  dataset  accuracy
experiment_id
exp_004           CNN    MNIST      0.93
exp_002           ViT  CIFAR10      0.96
exp_001           CNN    MNIST      0.91
exp_003        ResNet  CIFAR10      0.94

In [10]:
experiments = experiments.reset_index()

experiments

  experiment_id   model  dataset  accuracy
0       exp_004     CNN    MNIST      0.93
1       exp_002     ViT  CIFAR10      0.96
2       exp_001     CNN    MNIST      0.91
3       exp_003  ResNet  CIFAR10      0.94

In [11]:
experiments = experiments.set_index(["model", "dataset"])

experiments

               experiment_id  accuracy
model  dataset
CNN    MNIST         exp_004      0.93
ViT    CIFAR10       exp_002      0.96
CNN    MNIST         exp_001      0.91
ResNet CIFAR10       exp_003      0.94

In [12]:
experiments = experiments.sort_index()

experiments

               experiment_id  accuracy
model  dataset
CNN    MNIST         exp_004      0.93
       MNIST         exp_001      0.91
ResNet CIFAR10       exp_003      0.94
ViT    CIFAR10       exp_002      0.96

In [13]:
experiments = experiments.reset_index()

experiments

    model  dataset experiment_id  accuracy
0     CNN    MNIST       exp_004      0.93
1     CNN    MNIST       exp_001      0.91
2  ResNet  CIFAR10       exp_003      0.94
3     ViT  CIFAR10       exp_002      0.96

In [14]:
# set_index()
# Converts an existing column into the DataFrame's index.

# reindex()
# Changes the existing index to a specified set/order of labels.