**Categorical Data Practices**

```
# Convert
df["model"] = df["model"].astype("category")

# View categories
df["model"].cat.categories

# Add
df["model"].cat.add_categories(["ViT"])

# Remove
df["model"].cat.remove_categories(["ViT"])

# Remove unused
df["model"].cat.remove_unused_categories()

# Rename
df["model"].cat.rename_categories({...})

# Ordered categorical
pd.Categorical(
    values,
    categories=["low", "medium", "high"],
    ordered=True
)
```

---

In [4]:
import pandas as pd

##### Exercise — ML Experiment Dataset
```text
Create:

import pandas as pd

results = pd.DataFrame({
    "model": [
        "CNN", "ResNet", "CNN", "ViT",
        "ResNet", "CNN", "ViT", "ResNet"
    ],
    "status": [
        "success", "success", "failed", "success",
        "success", "failed", "success", "success"
    ],
    "priority": [
        "high", "medium", "low", "high",
        "medium", "low", "high", "medium"
    ],
    "confidence": [
        0.91, 0.95, 0.42, 0.93,
        0.88, 0.51, 0.97, 0.89
    ]
})

Perform the following:

Convert model, status, and priority to categorical data.
Display the categories of each column.
Add "Transformer" as a possible category for model.
Remove "Transformer" again.
Remove any unused categories.
Define the following ordered categories for priority:
low < medium < high
Sort the DataFrame by priority.
Rename the status categories:
success → completed
failed → error
Find how many unique categories exist in model.
Print the dtype of all three categorical columns.
In comments, explain the difference between:
category dtype
ML encoding such as converting categories to numeric values.

In [5]:
results = pd.DataFrame({
    "model": [
        "CNN", "ResNet", "CNN", "ViT",
        "ResNet", "CNN", "ViT", "ResNet"
    ],
    "status": [
        "success", "success", "failed", "success",
        "success", "failed", "success", "success"
    ],
    "priority": [
        "high", "medium", "low", "high",
        "medium", "low", "high", "medium"
    ],
    "confidence": [
        0.91, 0.95, 0.42, 0.93,
        0.88, 0.51, 0.97, 0.89
    ]
})

results

    model   status priority  confidence
0     CNN  success     high        0.91
1  ResNet  success   medium        0.95
2     CNN   failed      low        0.42
3     ViT  success     high        0.93
4  ResNet  success   medium        0.88
5     CNN   failed      low        0.51
6     ViT  success     high        0.97
7  ResNet  success   medium        0.89

In [6]:
results["model"] = results["model"].astype("category")
results["status"] = results["status"].astype("category")
results["priority"] = results["priority"].astype("category")

results.dtypes

model         category
status        category
priority      category
confidence     float64
dtype: object

In [7]:
print("Model categories:")
print(results["model"].cat.categories)

print("\nStatus categories:")
print(results["status"].cat.categories)

print("\nPriority categories:")
print(results["priority"].cat.categories)

Model categories:
Index(['CNN', 'ResNet', 'ViT'], dtype='str')

Status categories:
Index(['failed', 'success'], dtype='str')

Priority categories:
Index(['high', 'low', 'medium'], dtype='str')

In [8]:
results["model"] = results["model"].cat.add_categories(["Transformer"])

results["model"].cat.categories

Index(['CNN', 'ResNet', 'ViT', 'Transformer'], dtype='str')

In [9]:
results["model"] = results["model"].cat.remove_categories(["Transformer"])

results["model"].cat.categories

Index(['CNN', 'ResNet', 'ViT'], dtype='str')

In [10]:
results["model"] = results["model"].cat.remove_unused_categories()
results["status"] = results["status"].cat.remove_unused_categories()
results["priority"] = results["priority"].cat.remove_unused_categories()

results

    model   status priority  confidence
0     CNN  success     high        0.91
1  ResNet  success   medium        0.95
2     CNN   failed      low        0.42
3     ViT  success     high        0.93
4  ResNet  success   medium        0.88
5     CNN   failed      low        0.51
6     ViT  success     high        0.97
7  ResNet  success   medium        0.89

In [11]:
results["priority"] = results["priority"].cat.reorder_categories(
    ["low", "medium", "high"],
    ordered=True
)

results["priority"].cat.categories

Index(['low', 'medium', 'high'], dtype='str')

In [12]:
sorted_results = results.sort_values("priority")

sorted_results

    model   status priority  confidence
2     CNN   failed      low        0.42
5     CNN   failed      low        0.51
1  ResNet  success   medium        0.95
4  ResNet  success   medium        0.88
7  ResNet  success   medium        0.89
0     CNN  success     high        0.91
3     ViT  success     high        0.93
6     ViT  success     high        0.97

In [13]:
results["status"] = results["status"].cat.rename_categories({
    "success": "completed",
    "failed": "error"
})

results["status"].cat.categories

Index(['error', 'completed'], dtype='str')

In [14]:
model_category_count = results["model"].cat.categories.size

print(model_category_count)

3

In [15]:
print(results["model"].dtype)
print(results["status"].dtype)
print(results["priority"].dtype)

category
category
category

In [16]:
results

    model     status priority  confidence
0     CNN  completed     high        0.91
1  ResNet  completed   medium        0.95
2     CNN      error      low        0.42
3     ViT  completed     high        0.93
4  ResNet  completed   medium        0.88
5     CNN      error      low        0.51
6     ViT  completed     high        0.97
7  ResNet  completed   medium        0.89

In [17]:
# 1. What is the difference between category dtype and ML encoding?

# category dtype:
# A Pandas data type used to represent a limited set of categories
# efficiently and explicitly.

# ML encoding:
# A preprocessing technique that converts categorical values
# into numerical representations that can be used by ML algorithms.